/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellTasksRouteImport } from './routes/_shell/tasks'
import { Route as ShellQuizesRouteImport } from './routes/_shell/quizes'
import { Route as ShellLearningRouteImport } from './routes/_shell/learning'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellTasksRoute = ShellTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => ShellRoute,
} as any)
const ShellQuizesRoute = ShellQuizesRouteImport.update({
  id: '/quizes',
  path: '/quizes',
  getParentRoute: () => ShellRoute,
} as any)
const ShellLearningRoute = ShellLearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/learning': typeof ShellLearningRoute
  '/quizes': typeof ShellQuizesRoute
  '/tasks': typeof ShellTasksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/learning': typeof ShellLearningRoute
  '/quizes': typeof ShellQuizesRoute
  '/tasks': typeof ShellTasksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/learning': typeof ShellLearningRoute
  '/_shell/quizes': typeof ShellQuizesRoute
  '/_shell/tasks': typeof ShellTasksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/learning' | '/quizes' | '/tasks'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/learning' | '/quizes' | '/tasks'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/_shell/learning'
    | '/_shell/quizes'
    | '/_shell/tasks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/tasks': {
      id: '/_shell/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof ShellTasksRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/quizes': {
      id: '/_shell/quizes'
      path: '/quizes'
      fullPath: '/quizes'
      preLoaderRoute: typeof ShellQuizesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/learning': {
      id: '/_shell/learning'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof ShellLearningRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellLearningRoute: typeof ShellLearningRoute
  ShellQuizesRoute: typeof ShellQuizesRoute
  ShellTasksRoute: typeof ShellTasksRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellLearningRoute: ShellLearningRoute,
  ShellQuizesRoute: ShellQuizesRoute,
  ShellTasksRoute: ShellTasksRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
