/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellIndexRouteImport } from './routes/_shell/index'
import { Route as ShellDirectoriesRouteImport } from './routes/_shell/directories'
import { Route as ShellDirectoriesIndexRouteImport } from './routes/_shell/directories/index'
import { Route as ShellDirectoriesUsersRouteImport } from './routes/_shell/directories/users'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDirectoriesRoute = ShellDirectoriesRouteImport.update({
  id: '/directories',
  path: '/directories',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDirectoriesIndexRoute = ShellDirectoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellDirectoriesRoute,
} as any)
const ShellDirectoriesUsersRoute = ShellDirectoriesUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => ShellDirectoriesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/directories': typeof ShellDirectoriesRouteWithChildren
  '/directories/users': typeof ShellDirectoriesUsersRoute
  '/directories/': typeof ShellDirectoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof ShellIndexRoute
  '/directories/users': typeof ShellDirectoriesUsersRoute
  '/directories': typeof ShellDirectoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/directories': typeof ShellDirectoriesRouteWithChildren
  '/_shell/': typeof ShellIndexRoute
  '/_shell/directories/users': typeof ShellDirectoriesUsersRoute
  '/_shell/directories/': typeof ShellDirectoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/directories' | '/directories/users' | '/directories/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/directories/users' | '/directories'
  id:
    | '__root__'
    | '/_shell'
    | '/_shell/directories'
    | '/_shell/'
    | '/_shell/directories/users'
    | '/_shell/directories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/directories': {
      id: '/_shell/directories'
      path: '/directories'
      fullPath: '/directories'
      preLoaderRoute: typeof ShellDirectoriesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/directories/': {
      id: '/_shell/directories/'
      path: '/'
      fullPath: '/directories/'
      preLoaderRoute: typeof ShellDirectoriesIndexRouteImport
      parentRoute: typeof ShellDirectoriesRoute
    }
    '/_shell/directories/users': {
      id: '/_shell/directories/users'
      path: '/users'
      fullPath: '/directories/users'
      preLoaderRoute: typeof ShellDirectoriesUsersRouteImport
      parentRoute: typeof ShellDirectoriesRoute
    }
  }
}

interface ShellDirectoriesRouteChildren {
  ShellDirectoriesUsersRoute: typeof ShellDirectoriesUsersRoute
  ShellDirectoriesIndexRoute: typeof ShellDirectoriesIndexRoute
}

const ShellDirectoriesRouteChildren: ShellDirectoriesRouteChildren = {
  ShellDirectoriesUsersRoute: ShellDirectoriesUsersRoute,
  ShellDirectoriesIndexRoute: ShellDirectoriesIndexRoute,
}

const ShellDirectoriesRouteWithChildren =
  ShellDirectoriesRoute._addFileChildren(ShellDirectoriesRouteChildren)

interface ShellRouteChildren {
  ShellDirectoriesRoute: typeof ShellDirectoriesRouteWithChildren
  ShellIndexRoute: typeof ShellIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellDirectoriesRoute: ShellDirectoriesRouteWithChildren,
  ShellIndexRoute: ShellIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
