export const LLM_GUARD = 'ILlmGuardProvider'
export const LLM_CURATION = 'ILlmCurationProvider'
export const METRICS_COLLECTOR = 'MetricsCollector'
export const FIREBASE_FIRESTORE = 'FIREBASE_FIRESTORE'
export const FIREBASE_AUTH = 'FIREBASE_AUTH'
